name: Java CI with Gradle

on:
  push:
    branches: [ "develop" , "master"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Gradle Caching
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-


      - name: make application-develop.yml
        if: contains(github.ref, 'develop')
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_DEVELOP_YML }}" | base64 --decode > src/main/resources/application.yml
          find src

      - name: make application-master.yml
        if: contains(github.ref, 'master')
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_MASTER_YML }}" | base64 --decode > src/main/resources/application.yml
          find src


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test


      - name: Develop_Docker build
        if: contains(github.ref, 'develop')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t app .
          docker tag app ${{ secrets.DOCKER_USERNAME }}/amuse_develop:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/amuse_develop:latest

      - name: Master_Docker build
        if: contains(github.ref, 'master')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t app .
          docker tag app ${{ secrets.DOCKER_USERNAME }}/amuse_master:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/amuse_master:latest
      

      - name: Develop_Deploy
        if: contains(github.ref, 'develop')
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEVELOP_EC2_HOST_IPV4_DNS }} # EC2 인스턴스 퍼블릭 DNS
          username: ubuntu
          key: ${{ secrets.EC2_DEVELOP_PEM_KEY }} # pem 키
          # 도커 작업
          script: |
            if [ "$(sudo docker ps -aq)" ]; then
              sudo docker rm -f $(docker ps -aq)
            fi
            if [ "$(sudo docker images -q ${{ secrets.USERNAME }}/amuse_develop)" ]; then
              sudo docker rmi ${{ secrets.USERNAME }}/amuse_develop
            fi
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/amuse_develop:latest
            sudo docker run -d --log-driver=syslog -p 8075:8075 ${{ secrets.DOCKER_USERNAME }}/amuse_develop:latest
            sudo docker image prune -a -f

      - name: Master_Deploy
        if: contains(github.ref, 'master')
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ubuntu
          key: ${{ secrets.EC2_PEM_KEY }} # pem 키
          # 도커 작업
          script: |
            if [ "$(sudo docker ps -aq)" ]; then
              sudo docker rm -f $(docker ps -aq)
            fi
            if [ "$(sudo docker images -q ${{ secrets.USERNAME }}/amuse_master)" ]; then
              sudo docker rmi ${{ secrets.USERNAME }}/amuse_master
            fi
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/amuse_master:latest
            sudo docker run -d --log-driver=syslog -p 8075:8075 ${{ secrets.DOCKER_USERNAME }}/amuse_master:latest
            sudo docker image prune -a -f
